apiVersion: apps/v1
kind: Deployment
metadata:
    name: cloudbase-ssh-postgres-depl
spec:
    selector:
        matchLabels:
            app: cloudbase-ssh-postgres-depl
    template:
        metadata:
            labels:
                app: cloudbase-ssh-postgres-depl
        spec:
            containers:
                - name: cloudbase-ssh-postgres-depl
                  image: vnavaneeth/static-site-hosting-postgres
                  #   image: postgres:10.1
                  ports:
                      - containerPort: 5432
                  env:
                      - name: POSTGRES_MULTIPLE_DATABASES
                        value: serverless
                      - name: POSTGRES_DB
                        value: cloudbase
                      - name: POSTGRES_USER
                        value: cloudbase
                      - name: POSTGRES_PASSWORD
                        value: cloudbase
                #   resources:
                # limits:
                #   memory: '128Mi'
                #   cpu: '500m'

---
apiVersion: v1
kind: Service
metadata:
    name: cloudbase-ssh-postgres-svc
spec:
    selector:
        app: cloudbase-ssh-postgres-depl
    type: ClusterIP
    ports:
        - port: 5432
          targetPort: 5432
