apiVersion: v1
kind: Service
metadata:
    name: cloudbase-ssh-svc
spec:
    selector:
        app: cloudbase-ssh-depl
    type: ClusterIP
    ports:
        - port: 4000
          targetPort: 4000

---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: everything-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: everything-role
    # namespace: default
rules:
    - apiGroups:
          - ''
          - 'apps'
      resources:
          - '*'
      verbs:
          - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: everything-sa
    # namespace: foo
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: everything-role
subjects:
    - kind: ServiceAccount
      name: everything-sa
      namespace: default

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: cloudbase-ssh-depl
spec:
    selector:
        matchLabels:
            app: cloudbase-ssh-depl
    template:
        metadata:
            labels:
                app: cloudbase-ssh-depl
        spec:
            serviceAccountName: everything-sa
            containers:
                - name: cloudbase-ssh-depl
                  image: vnavaneeth/cloudbase-ssh
                  imagePullPolicy: 'Never'
                  # resources:
                  # limits:
                  #   memory: "128Mi"
                  #   cpu: "500m"
                  # ports:
                  # - containerPort: <Port>
